version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  pass-gen:
    lang: python3-http
    handler: ./pass-gen
    image: jixjocelyn/pass-gen:0.0.3
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: "postgresql://neondb_owner:npg_fnFebDpY7zr4@ep-snowy-mud-a9jgtwmg-pooler.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

