apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  username: Y29mcmFw          # cofrap
  password: Y29mcmFwMTIz   # cofrap123

# echo -n 'monmotdepasse' | base64
# en bash