apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  username: cofrap          # postgres
  password: cofrap123  # securepassword

# echo -n 'monmotdepasse' | base64
# en bash