apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: cofrap
  labels:
    app: postgres
type: Opaque
data:
  # Les valeurs sont encodées en base64
  # echo -n "cofrap" | base64
  username: Y29mcmFw
  # echo -n "cofrap123" | base64
  password: Y29mcmFwMTIz
  # echo -n "cofrap" | base64
  database: Y29mcmFw 